# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1f5txRM8Yprrhs6fg6dFWxpA0NRFzXH
"""

cities=['pakistan','india','london','karachi','hyderabad','sukkhur','chichago','malaysia','melbourne','brimingham']
cities.sort()
print (cities)

cities=['pakistan','india','london','karachi','hyderabad','sukkhur','chichago','malaysia','melbourne','brimingham']
cities.sort(reverse=True)
print (cities)

cities=['pakistan','india','london','karachi','hyderabad','sukkhur','chichago','malaysia','melbourne','brimingham']
king=cities[4:8]
print(king)

cities=['pakistan','india','london','karachi','hyderabad','sukkhur','chichago','malaysia','melbourne','brimingham']
print(sorted(cities))

